### ISSUE TITLE
Question Regarding Scaling and Transformation:

### ISSUE THREAD

**Issue by BrandonKMLee** [solegalli/feature-engineering-for-machine-learning#12]
These two features are often put together in sk-learn and other libraries, but there are some distinction between the two. When should they be used, or if used together, what is the best order of operations?
- https://github.com/solegalli/feature-engineering-for-machine-learning/tree/main/Section-07-Variable-Transformation
- https://github.com/solegalli/feature-engineering-for-machine-learning/tree/main/Section-10-Feature-Scaling

**Comment by solegalli** [comment]
Hey @BrandonKMLee 

Scaling is always the last step in the pipeline.

Please ask questions in the course, because I do not monitor the issues regularly.
