### ISSUE TITLE
Value error

### ISSUE THREAD

**Issue by Himanshu0312** [solegalli/feature-engineering-for-machine-learning#3]
This is regarding 'Automatic-Imputation-Method-Detection-Sklearn'

I am getting the following error when using Auto-mpg dataset from UCI,
ValueError: A given column is not a column of the dataframe
ValueError: 'mpg' is not in list

My workbook,
https://colab.research.google.com/drive/1ga5cFL-qnUWkyOSV2XG8VoSzPaeH-qtx?usp=sharing

Can you please help me fix this?

**Comment by solegalli** [comment]
It looks like you are trying to impute a columns that is not in the df. 

I don't check issues regularly for this repo. Would you mind asking the questions in the course?

Cheers
Sole
