### ISSUE TITLE
 ModuleNotFoundError: No module named 'feature_engine.encoding'

### ISSUE THREAD

**Issue by fealgu1** [solegalli/feature-engineering-for-machine-learning#4]
ModuleNotFoundError: No module named 'feature_engine_categorical'
I've un/installed the package but this module is not found. Any thoughts?

**Comment by solegalli** [comment]
Sorry, I don't regularly check issues in this repo. Can you please ask the question in the course or in stackoverflow?

It seems to me that it might be version issue. feature_engine.encoding should work.
